language: objective-c
osx_image: xcode9.4
gemfile: Gemfile

branches:
  only:
    - master

cache:
  - bundler
  - cocoapods

env:
   global:
     - LANG=en_US.UTF-8

     - WORKSPACE="ReactiveLists.xcworkspace"

     - FRAMEWORK_SCHEME="ReactiveLists"
     - EXAMPLE_SCHEME="Example"

   matrix:
     - DESTINATION="OS=9.3,name=iPhone 6s"   SCHEME="$FRAMEWORK_SCHEME" POD_LINT="YES" CODE_COVERAGE="NO"
     - DESTINATION="OS=10.3.1,name=iPhone 7" SCHEME="$FRAMEWORK_SCHEME" POD_LINT="NO" CODE_COVERAGE="NO"
     - DESTINATION="OS=11.4,name=iPhone X"   SCHEME="$FRAMEWORK_SCHEME" POD_LINT="NO" CODE_COVERAGE="YES"

# Note: travis installs ruby dependencies using bundler automatically, when there's a Gemfile

script:
  - set -o pipefail
  - xcodebuild -version -sdk

  - if [ $POD_LINT == "YES" ]; then
        bundle exec pod lib lint;
    fi

  - killall Simulator || true

  - xcodebuild test -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -sdk "iphonesimulator" -destination "$DESTINATION" -configuration Debug -enableCodeCoverage "$CODE_COVERAGE" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | bundle exec xcpretty -c

  - if [ $BUILD_EXAMPLE == "YES" ]; then
        xcodebuild build -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "iphonesimulator" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | bundle exec xcpretty -c;
    fi

  - bundle exec danger

after_success:
  - bash <(curl -s https://codecov.io/bash)
