name: CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.1.app/Contents/Developer
  WORKSPACE: ReactiveLists.xcworkspace
  LIBRARY_SCHEME: ReactiveLists
  EXAMPLE_APP_SCHEME: Example
  IOS_SDK: iphonesimulator14.1

jobs:
  iOS:
    name: iOS Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=14.1,name=iPhone 11"]
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v3
        with:
          ruby-version: 3.0
      - name: Bundle update
        run: bundle update
      - name: Bundle Install
        run: bundle install
      - uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        run: bundle exec pod install
      - name: Run Tests
        run: |
          set -o pipefail
          xcodebuild clean
          xcodebuild test -workspace "$WORKSPACE" -scheme "$LIBRARY_SCHEME" -destination "${{ matrix.destination }}" -configuration Debug -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty -c
          xcodebuild test -workspace "$WORKSPACE" -scheme "$EXAMPLE_APP_SCHEME" -destination "${{ matrix.destination }}" -configuration Debug -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty -c
      - name: Run Code Coverage
        run: bash <(curl -s https://codecov.io/bash)
